### ISSUE TITLE
Crash with shadersmod (Optifine's)

### ISSUE THREAD

**Issue by Ghostlyr** [zlainsama/SkinPort#27]
- Choose shaders with shader options (e. g. Oceano Shaders)
- Change any shader option (e. g. MoutionBlur) and save it
- Close game
- Try launch again
- ...

```
java.lang.ExceptionInInitializerError
	at net.minecraft.client.model.ModelBiped.<init>(SourceFile:25)
	at net.minecraft.client.model.ModelEnderman.<init>(SourceFile:11)
	at net.minecraft.client.renderer.entity.RenderEnderman.<init>(RenderEnderman.java:31)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:141)
	at net.minecraft.client.renderer.entity.RenderManager.<clinit>(RenderManager.java:101)
	at shadersmod.uniform.ShaderParameterBool.<init>(ShaderParameterBool.java:43)
	at shadersmod.uniform.ShaderParameterBool.<clinit>(ShaderParameterBool.java:18)
	at shadersmod.uniform.ShaderExpressionResolver.registerExpressions(ShaderExpressionResolver.java:52)
	at shadersmod.uniform.ShaderExpressionResolver.<init>(ShaderExpressionResolver.java:29)
	at shadersmod.client.ShaderPackParser.parseCustomUniform(ShaderPackParser.java:805)
	at shadersmod.client.ShaderPackParser.parseCustomUniforms(ShaderPackParser.java:769)
	at shadersmod.client.Shaders.loadShaderPackProperties(Shaders.java:1077)
	at shadersmod.client.Shaders.loadShaderPack(Shaders.java:963)
	at shadersmod.client.Shaders.loadConfig(Shaders.java:705)
	at shadersmod.client.Shaders.startup(Shaders.java:1900)
	at Config.initDisplay(Config.java:216)
	at net.minecraft.client.renderer.OpenGlHelper.func_77474_a(OpenGlHelper.java:82)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:516)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:965)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
Caused by: java.lang.NullPointerException
	at cpw.mods.fml.common.Loader.isModLoaded(Loader.java:619)
	at lain.mods.skinport.init.forge.asm.Hooks.<clinit>(Hooks.java:23)
	... 29 more
```

MC 1.7.10
Forge 1614
OptiFine_1.7.10_HD_U_E7
SkinPort-1.7.10-v10a

**Comment by zlainsama** [comment]
@Ghostlyr 
Please test [version 1.7.10-v10b](https://github.com/zlainsama/SkinPort/releases/tag/1.7.10-v10b) to see if it actually fixes the issue.

**Comment by Ghostlyr** [comment]
It works! Thanks.

**Comment by Ghostlyr** [comment]
Hah, sorry. Next launch:

```
java.lang.ExceptionInInitializerError
	at shadersmod.uniform.ShaderParameterBool.<init>(ShaderParameterBool.java:43)
	at shadersmod.uniform.ShaderParameterBool.<clinit>(ShaderParameterBool.java:18)
	at shadersmod.uniform.ShaderExpressionResolver.registerExpressions(ShaderExpressionResolver.java:52)
	at shadersmod.uniform.ShaderExpressionResolver.<init>(ShaderExpressionResolver.java:29)
	at shadersmod.client.ShaderPackParser.parseCustomUniform(ShaderPackParser.java:805)
	at shadersmod.client.ShaderPackParser.parseCustomUniforms(ShaderPackParser.java:769)
	at shadersmod.client.Shaders.loadShaderPackProperties(Shaders.java:1077)
	at shadersmod.client.Shaders.loadShaderPack(Shaders.java:963)
	at shadersmod.client.Shaders.loadConfig(Shaders.java:705)
	at shadersmod.client.Shaders.startup(Shaders.java:1900)
	at Config.initDisplay(Config.java:216)
	at net.minecraft.client.renderer.OpenGlHelper.func_77474_a(OpenGlHelper.java:82)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:516)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:965)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
Caused by: java.lang.NullPointerException
	at cpw.mods.fml.common.Loader.isModLoaded(Loader.java:619)
	at lain.mods.skinport.init.forge.ClientProxy.setupRenderers(ClientProxy.java:180)
	at lain.mods.skinport.init.forge.asm.Hooks.RenderManager_postRenderManagerInit(Hooks.java:89)
	at net.minecraft.client.renderer.entity.RenderManager.<init>(RenderManager.java:192)
	at net.minecraft.client.renderer.entity.RenderManager.<clinit>(RenderManager.java:101)
	... 24 more
```

**Comment by zlainsama** [comment]
@Ghostlyr 
Please test [version 1.7.10-v10c](https://github.com/zlainsama/SkinPort/releases/tag/1.7.10-v10c) to see if it actually fixed this issue.

**Comment by Ghostlyr** [comment]
No longer crashes (i hope so)
